inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'client/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'bin/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/RaiseArgs:
  EnforcedStyle: compact
Metrics/ModuleLength:
  Max: 300
