inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Bundler/OrderedGems:
  Enabled: false
Rails:
  Enabled: true
Rails/ApplicationRecord:
  Exclude:
    - 'config/initializers/doorkeeper.rb'
Rails/SkipsModelValidations:
  Enabled: false
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/RaiseArgs:
  EnforcedStyle: compact
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/LineLength:
  Max: 120
Metrics/ModuleLength:
  Max: 300
