AllCops:
  Rails:
    Enabled: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
Metrics/LineLength:
  Max: 100
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/RaiseArgs:
  EnforcedStyle: compact
