AllCops:
  DisabledByDefault: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Rails:
  Enabled: true
Style/ExtraSpacing:
  Enabled: true
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/InitialIndentation:
  Enabled: true
Style/FirstParameterIndentation:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/Lambda:
  Enabled: true
Style/SpaceAfterNot:
  Enabled: true
Style/RedundantSelf:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true
Style/Tab:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Style/TrailingCommaInLiteral:
  Enabled: true
Style/TrailingWhitespace:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
Style/UnneededCapitalW:
  Enabled: true
