inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Rails:
  Enabled: true
Style/ExtraSpacing:
  Enabled: true
Metrics/LineLength:
  Max: 120
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/InitialIndentation:
  Enabled: true
Style/FirstParameterIndentation:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/Lambda:
  Enabled: true
Style/SpaceAfterNot:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/TrailingBlankLines:
  Enabled: true
Style/Tab:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Style/TrailingCommaInLiteral:
  Enabled: true
Style/TrailingWhitespace:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
Style/UnneededCapitalW:
  Enabled: true
Style/UnneededInterpolation:
  Enabled: true
Style/UnneededPercentQ:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/EndInMethod:
  Enabled: true
Lint/EndAlignment:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/ElseLayout:
  Enabled: true
Lint/EachWithObjectArgument:
  Enabled: true
Lint/DuplicatedKey:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DefEndAlignment:
  Enabled: true

Style/AccessModifierIndentation:
  Enabled: true
Style/AlignArray:
  Enabled: true
Style/AlignHash:
  Enabled: true
Style/AlignParameters:
  Enabled: true
Style/BracesAroundHashParameters:
  Enabled: true
Style/CaseIndentation:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/BlockDelimiters:
  Enabled: true
