AllCops:
  DisabledByDefault: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Rails:
  Enabled: true
Style/ExtraSpacing:
  Enabled: true
Style/IfUnlessModifier:
  MaxLineLength: 100
Style/WhileUntilModifier:
  MaxLineLength: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
