version: '2'

services:
  app:
    build: .
    image: fletcher91/argu
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
      - mailcatcher
  sidekiq:
    image: fletcher91/argu
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
      - mailcatcher
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
  redis:
    image: redis:2.8.17
    ports:
      - "6379:6379"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
