app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  env_file:
    - ./.env
  links:
    - postgres
postgres:
  image: postgres:9.4
  ports:
    - "5432"
