production:
  adapter: mysql2
  encoding: utf8
  database: argu_production
  pool: 5
  username: argu_prod
  password: Op3ndebate

development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: argu_development
  pool: 5
  username: arguroot
  password: opendebate
