development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
  schema_search_path: 'public,shared_extensions'
test:
  <<: *default
  database: argu_test
production: &production
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
staging:
  <<: *production
