FROM fletcher91/ruby-vips-qt-unicorn:latest

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD Gemfile /usr/src/app/
ADD Gemfile.lock /usr/src/app/
RUN bundle install --deployment --path ../vendor/bundle

ENV POSTGRESQL_ADDRESS 'db'
ENV POSTGRESQL_PORT '5432'
ENV POSTGRESQL_USERNAME 'postgres'
ENV POSTGRESQL_PASSWORD ''
ENV POSTGRESQL_DATABASE 'argu'
ENV RAILS_ENV 'production'
ENV REDIS_HOST 'redis'
ENV REDIS_PORT '6379'

VOLUME ["/usr/src/app"]

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
