require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatementsController do

  describe "as a user" do
    login_user

    describe "GET index" do
      it "assigns all statements as @statements" do
        statement = FactoryGirl.create(:statement)
        get :index, {}
        assigns(:statements).should eq([statement])
      end
    end

    describe "GET show" do
      it "assigns the requested statement as @statement" do
        statement = FactoryGirl.create(:statement)
        get :show, {:id => statement.to_param}
        assigns(:statement).should eq(statement)
      end
    end

    describe "GET new" do
      it "assigns a new statement as @statement" do
        get :new, {}
        assigns(:statement).should be_a_new(Statement)
      end
    end

    describe "GET edit" do
      it "assigns the requested statement as @statement" do
        statement = FactoryGirl.create(:statement)
        get :edit, {:id => statement.to_param}
        assigns(:statement).should eq(statement)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Statement" do
          expect {
            post :create, {:statement => FactoryGirl.attributes_for(:statement) }
          }.to change(Statement, :count).by(1)
        end

        it "assigns a newly created statement as @statement" do
          post :create, {:statement => FactoryGirl.attributes_for(:statement) }
          assigns(:statement).should be_a(Statement)
          assigns(:statement).should be_persisted
        end

        it "redirects to the created statement" do
          post :create, {:statement => FactoryGirl.attributes_for(:statement) }
          response.should redirect_to(Statement.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved statement as @statement" do
          # Trigger the behavior that occurs when invalid params are submitted
          Statement.any_instance.stub(:save).and_return(false)
          post :create, {:statement => {}}
          assigns(:statement).should be_a_new(Statement)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Statement.any_instance.stub(:save).and_return(false)
          post :create, {:statement => {}}
          response.should render_template('form')
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "redirects to root" do
          statement = FactoryGirl.create(:statement)
          put :update, {:id => statement.to_param, :statement => FactoryGirl.attributes_for(:statement) }
          response.should redirect_to(root_path)
        end
      end

      describe "with invalid params" do

        it "redirect to root" do
          statement = FactoryGirl.create(:statement)
          # Trigger the behavior that occurs when invalid params are submitted
          Statement.any_instance.stub(:save).and_return(false)
          put :update, {:id => statement.to_param, :statement => {}}
          response.should redirect_to(root_path)
        end
      end
    end

    describe "DELETE destroy" do
      it "doesn't destroy the requested statement" do
        statement = FactoryGirl.create(:statement)
        expect {
          delete :destroy, {:id => statement.to_param}
        }.to change(Statement, :count).by(0)
      end

      it "redirects to root" do
        statement = FactoryGirl.create(:statement)
        delete :destroy, {:id => statement.to_param}
        response.should redirect_to(root_path)
      end
    end

  end

  describe "as admin" do
    login_admin

    describe "PUT update" do
      describe "with valid params" do

        it "updates the requested statement" do
          statement = FactoryGirl.create(:statement)
          Statement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => statement.to_param, :statement => {'these' => 'params'}}
        end

        it "assigns the requested statement as @statement" do
          statement = FactoryGirl.create(:statement)
          put :update, {:id => statement.to_param, :statement => FactoryGirl.attributes_for(:statement) }
          assigns(:statement).should eq(statement)
        end

        it "redirects to the statement" do
          statement = FactoryGirl.create(:statement)
          put :update, {:id => statement.to_param, :statement => FactoryGirl.attributes_for(:statement) }
          response.should redirect_to(statement)
        end
      end

      describe "with invalid params" do
        it "assigns the statement as @statement" do
          statement = FactoryGirl.create(:statement)
          # Trigger the behavior that occurs when invalid params are submitted
          Statement.any_instance.stub(:save).and_return(false)
          put :update, {:id => statement.to_param, :statement => {}}
          assigns(:statement).should eq(statement)
        end

        it "re-renders the 'edit' template" do
          statement = FactoryGirl.create(:statement)
          # Trigger the behavior that occurs when invalid params are submitted
          Statement.any_instance.stub(:save).and_return(false)
          put :update, {:id => statement.to_param, :statement => {}}
          response.should render_template('statements/form')
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested statement" do
        statement = FactoryGirl.create(:statement)
        expect {
          delete :destroy, {:id => statement.to_param, destroy: true}
        }.to change(Statement, :count).by(-1)
      end

      it "redirects to the statements list" do
        statement = FactoryGirl.create(:statement)
        delete :destroy, {:id => statement.to_param, destroy: true}
        response.should redirect_to(statements_url)
      end
    end
  end

end
