require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MotionsController do

  describe "as a user" do
    login_user

    describe "GET index" do
      it "assigns all motions as @motions" do
        motion = FactoryGirl.create(:motion)
        get :index, {}
        assigns(:motions).should eq([motion])
      end
    end

    describe "GET show" do
      it "assigns the requested motion as @motion" do
        motion = FactoryGirl.create(:motion)
        get :show, {:id => motion.to_param}
        assigns(:motion).should eq(motion)
      end
    end

    describe "GET new" do
      it "assigns a new motion as @motion" do
        get :new, {}
        assigns(:motion).should be_a_new(Motion)
      end
    end

    describe "GET edit" do
      it "assigns the requested motion as @motion" do
        motion = FactoryGirl.create(:motion)
        get :edit, {:id => motion.to_param}
        assigns(:motion).should eq(motion)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Motion" do
          expect {
            post :create, {:motion => FactoryGirl.attributes_for(:motion) }
          }.to change(Motion, :count).by(1)
        end

        it "assigns a newly created motion as @motion" do
          post :create, {:motion => FactoryGirl.attributes_for(:motion) }
          assigns(:motion).should be_a(Motion)
          assigns(:motion).should be_persisted
        end

        it "redirects to the created motion" do
          post :create, {:motion => FactoryGirl.attributes_for(:motion) }
          response.should redirect_to(Motion.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved motion as @motion" do
          # Trigger the behavior that occurs when invalid params are submitted
          Motion.any_instance.stub(:save).and_return(false)
          post :create, {:motion => {}}
          assigns(:motion).should be_a_new(Motion)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          Motion.any_instance.stub(:save).and_return(false)
          post :create, {:motion => {}}
          response.should render_template('form')
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "redirects to root" do
          motion = FactoryGirl.create(:motion)
          put :update, {:id => motion.to_param, :motion => FactoryGirl.attributes_for(:motion) }
          response.should redirect_to(root_path)
        end
      end

      describe "with invalid params" do

        it "redirect to root" do
          motion = FactoryGirl.create(:motion)
          # Trigger the behavior that occurs when invalid params are submitted
          Motion.any_instance.stub(:save).and_return(false)
          put :update, {:id => motion.to_param, :motion => {}}
          response.should redirect_to(root_path)
        end
      end
    end

    describe "DELETE destroy" do
      it "doesn't destroy the requested motion" do
        motion = FactoryGirl.create(:motion)
        expect {
          delete :destroy, {:id => motion.to_param}
        }.to change(Motion, :count).by(0)
      end

      it "redirects to root" do
        motion = FactoryGirl.create(:motion)
        delete :destroy, {:id => motion.to_param}
        response.should redirect_to(root_path)
      end
    end

  end

  describe "as admin" do
    login_admin

    describe "PUT update" do
      describe "with valid params" do

        it "updates the requested motion" do
          motion = FactoryGirl.create(:motion)
          Motion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
          put :update, {:id => motion.to_param, :motion => {'these' => 'params'}}
        end

        it "assigns the requested motion as @motion" do
          motion = FactoryGirl.create(:motion)
          put :update, {:id => motion.to_param, :motion => FactoryGirl.attributes_for(:motion) }
          assigns(:motion).should eq(motion)
        end

        it "redirects to the motion" do
          motion = FactoryGirl.create(:motion)
          put :update, {:id => motion.to_param, :motion => FactoryGirl.attributes_for(:motion) }
          response.should redirect_to(motion)
        end
      end

      describe "with invalid params" do
        it "assigns the motion as @motion" do
          motion = FactoryGirl.create(:motion)
          # Trigger the behavior that occurs when invalid params are submitted
          Motion.any_instance.stub(:save).and_return(false)
          put :update, {:id => motion.to_param, :motion => {}}
          assigns(:motion).should eq(motion)
        end

        it "re-renders the 'edit' template" do
          motion = FactoryGirl.create(:motion)
          # Trigger the behavior that occurs when invalid params are submitted
          Motion.any_instance.stub(:save).and_return(false)
          put :update, {:id => motion.to_param, :motion => {}}
          response.should render_template('motions/form')
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested motion" do
        motion = FactoryGirl.create(:motion)
        expect {
          delete :destroy, {:id => motion.to_param, destroy: true}
        }.to change(Motion, :count).by(-1)
      end

      it "redirects to the motions list" do
        motion = FactoryGirl.create(:motion)
        delete :destroy, {:id => motion.to_param, destroy: true}
        response.should redirect_to(motions_url)
      end
    end
  end

end
